@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('contdownload_loans')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('contbuild_loans')
        {
            steps
            {
                script
                {
                    cicd.mavenBuild()
                }
            }
        }
    }
}
